/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import {useQuery} from '@tanstack/react-query';
import type {UseQueryOptions, QueryFunction, UseQueryResult, QueryKey} from '@tanstack/react-query';
import type {Notification} from './model';
import {httpCall} from '../utils/httpCall';
import type {ErrorType} from '../utils/httpCall';

/**
 * お知らせの一覧を取得します。
 * @summary お知らせ一覧取得
 */
export const getListNotifications = (signal?: AbortSignal) => {
  return httpCall<Notification[]>({url: `/notifications`, method: 'get', signal});
};

export const getGetListNotificationsQueryKey = () => [`/notifications`] as const;

export const getGetListNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListNotifications>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getListNotifications>>, TError, TData>;
}): UseQueryOptions<Awaited<ReturnType<typeof getListNotifications>>, TError, TData> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetListNotificationsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListNotifications>>> = ({signal}) =>
    getListNotifications(signal);

  return {queryKey, queryFn, ...queryOptions};
};

export type GetListNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof getListNotifications>>>;
export type GetListNotificationsQueryError = ErrorType<unknown>;

export const useGetListNotifications = <
  TData = Awaited<ReturnType<typeof getListNotifications>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getListNotifications>>, TError, TData>;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const queryOptions = getGetListNotificationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryOptions.queryKey;

  return query;
};
