/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import {useQuery} from '@tanstack/react-query';
import type {UseQueryOptions, QueryFunction, UseQueryResult, QueryKey} from '@tanstack/react-query';
import type {TermsOfService} from './model';
import {httpCall} from '../../../bases/http-client/httpCall';
import type {ErrorType} from '../../../bases/http-client/httpCall';

/**
 * 有効な利用規約を取得します。このAPIの呼び出しには認証情報は不要です。

 * @summary 有効な利用規約の取得
 */
export const getTerms = (signal?: AbortSignal) => {
  return httpCall<TermsOfService>({url: `/terms`, method: 'get', signal});
};

export const getGetTermsQueryKey = () => [`/terms`] as const;

export const getGetTermsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTerms>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getTerms>>, TError, TData>;
}): UseQueryOptions<Awaited<ReturnType<typeof getTerms>>, TError, TData> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTermsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTerms>>> = ({signal}) => getTerms(signal);

  return {queryKey, queryFn, ...queryOptions};
};

export type GetTermsQueryResult = NonNullable<Awaited<ReturnType<typeof getTerms>>>;
export type GetTermsQueryError = ErrorType<unknown>;

export const useGetTerms = <TData = Awaited<ReturnType<typeof getTerms>>, TError = ErrorType<unknown>>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getTerms>>, TError, TData>;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const queryOptions = getGetTermsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryOptions.queryKey;

  return query;
};
