name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  release-drafter:
    permissions:
      # Permissions for Release Drafter
      # - write permission is required to create a github release
      contents: write
      # - write permission is required for autolabeler
      #   otherwise, read permission is required at least
      pull-requests: write
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
    runs-on: ubuntu-22.04
    steps:
      # Release Drafter: https://github.com/marketplace/actions/release-drafter
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          config-name: release-drafter.yml
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
